package hackerrank.booking.com.backendcodesprint;

import java.util.*;

/**
 * Created by andrew on 22/09/16.
 */

class Point {
    String name;
    double latitude, longitude;

    Point(String n, double lat, double lon) {
        this.name = n;
        this.latitude = lat;
        this.longitude = lon;
    }

    public String toString() {
        return name;
    }

    public int hashCode() {
        return this.name.hashCode();
    }
}

public class CouplingPassions {
    //int EARTH_RADIUS = 6371000;
    static double distance_between(Point point1, Point point2) {
        int EARTH_RADIUS = 6371;//in km
        double point1_lat_in_radians = Math.toRadians(point1.latitude);
        double point2_lat_in_radians = Math.toRadians(point2.latitude);
        double point1_long_in_radians = Math.toRadians(point1.longitude);
        double point2_long_in_radians = Math.toRadians(point2.longitude);

        return Math.acos(Math.sin(point1_lat_in_radians) * Math.sin(point2_lat_in_radians) +
                Math.cos(point1_lat_in_radians) * Math.cos(point2_lat_in_radians) *
                        Math.cos(point2_long_in_radians - point1_long_in_radians)) * EARTH_RADIUS;
    }

    public static void main(String[] args) {

        /* Enter your code here. Read input from STDIN. Print output to STDOUT. Your class should be named Solution. */
        Set<String> guestsPassions = new HashSet<>();
        Map<Point, Set<String>> destinations = new HashMap<>();
        Scanner in = new Scanner(System.in);
        int guests = in.nextInt();
        in.nextLine();
        for (int i = 0; i < guests; i++) {
            int numP = in.nextInt();
            for (int j = 0; j < numP; j++) {
                guestsPassions.add(in.next());
            }
            in.nextLine();
        }
        //prepare destinations map
        int points = in.nextInt();
        in.nextLine();
        for (int i = 0; i < points; i++) {
            Point p = new Point(in.next(), in.nextDouble(), in.nextDouble());
            Set<String> attractions = new HashSet<String>();
            int attractNum = in.nextInt();
            for (int j = 0; j < attractNum; j++) {
                attractions.add(in.next());
            }
            destinations.put(p, attractions);
            if (in.hasNextLine()) {
                in.nextLine();
            }
        }

        in.close();
        Map<Integer, Set<String>> stats = new TreeMap<Integer, Set<String>>();

        for (Map.Entry<Point, Set<String>> e1 : destinations.entrySet()) {
            for (Map.Entry<Point, Set<String>> e2 : destinations.entrySet()) {
                if (!e1.getKey().toString().equals(e2.getKey().toString())) {
                    Set<String> attractSet = new HashSet<String>();
                    attractSet.addAll(e1.getValue());
                    attractSet.addAll(e2.getValue());
                    attractSet.retainAll(guestsPassions);
                    if (stats.containsKey(attractSet.size())) {
                        stats.get(attractSet.size()).add(
                                //making order correct for result, also avoid duplications
                                (e1.getKey().toString().compareTo(e2.getKey().toString()) <= 0 ? e1.getKey() + " " + e2.getKey() : e2.getKey() + " " + e1.getKey()));
                    } else {
                        Set<String> aSet = new HashSet<String>();
                        aSet.add((e1.getKey().toString().compareTo(e2.getKey().toString()) <= 0 ? e1.getKey() + " " + e2.getKey() : e2.getKey() + " " + e1.getKey()));
                        stats.put(attractSet.size(), aSet);
                    }
                    // System.out.println(attractSet.size()+":"+stats.get(attractSet.size()));
                    /*
                    System.out.println((e1.getKey().toString().compareTo(e2.getKey().toString()) <=0?e1.getKey()+" "+e2.getKey():e2.getKey()+" "+e1.getKey())+":"+attractSet);
                    */
                }
            }
        }
        //get a setof points that has most common passions
        Set<String> pointsSet = null;
        for (Map.Entry<Integer, Set<String>> e : stats.entrySet()) {
            pointsSet = e.getValue();//get last one
        }
        //System.out.println(pointsSet);
        TreeMap<Double, String> orderByDistance = new TreeMap<Double, String>();
        for (String s : pointsSet) {
            String[] pointPair = s.split(" ");
            Point p1 = null;
            for (Point p : destinations.keySet()) {
                if (p.toString().equals(pointPair[0])) {
                    p1 = p;
                    break;
                }
            }
            Point p2 = null;
            for (Point p : destinations.keySet()) {
                if (p.toString().equals(pointPair[1])) {
                    p2 = p;
                    break;
                }
            }
            double distance = distance_between(p1, p2);
            orderByDistance.put(distance, s);
        }
        String result = "";
        for (Map.Entry<Double, String> e : orderByDistance.entrySet()) {
            result = e.getValue();
            //get first one
            break;
        }
        System.out.println(result);
    }
}
/*
input
4
4 theme_fishing theme_coffee theme_photography theme_musicals
2 theme_archeology theme_shopping_clothes
1 theme_fam_friendly
1 theme_golf
100
paris 48.856682174906126 2.3514763824641705 30 theme_museums synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture theme_monuments theme_architecture theme_shopping synonym_destfinder_themes_history theme_food synonym_destfinder_themes_art review_destination_themes_romantic theme_city_walks theme_walking synonym_destfinder_themes_restaurants theme_fine_art_museums theme_ambiance theme_atmosphere theme_city_trip synonym_destfinder_themes_cafes theme_convenient_public_transport theme_gourmet theme_tourism theme_ancient_landmarks theme_parks theme_promenade theme_cathedral theme_luxury_brand_shopping theme_art_galleries theme_old_town theme_scenery theme_churches
barcelona 41.38710021972656 2.1700100898742676 30 theme_architecture synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture theme_food theme_shopping theme_beach theme_city_trip theme_museums theme_monuments theme_tapas synonym_destfinder_themes_art theme_nightlife theme_city_walks theme_ambiance theme_atmosphere theme_old_town theme_walking theme_friendly_people synonym_destfinder_themes_restaurants synonym_destfinder_themes_history theme_convenient_public_transport theme_warm_weather theme_cathedral theme_parks theme_sunny theme_tourism theme_local_food theme_markets theme_promenade theme_beach_walks
rome 41.895870208740234 12.482617378234863 30 synonym_destfinder_themes_history theme_monuments theme_museums theme_ancient_landmarks synonym_destfinder_themes_culture synonym_destfinder_themes_sightseeing theme_food theme_architecture synonym_destfinder_themes_art theme_shopping theme_roman_ruins theme_city_walks theme_old_town theme_churches theme_walking theme_fountain theme_atmosphere theme_ambiance theme_archeology synonym_destfinder_themes_restaurants review_destination_themes_romantic theme_local_food theme_cathedral theme_city_trip theme_friendly_people theme_tourism theme_pizza theme_traditional_food theme_fine_dining theme_warm_weather
newyork 40.76807403564453 -73.98189544677734 30 theme_shopping synonym_destfinder_themes_sightseeing theme_museums synonym_destfinder_themes_entertainment theme_food theme_theatre synonym_destfinder_themes_culture synonym_destfinder_themes_restaurants theme_city_walks theme_walking theme_city_trip theme_parks theme_architecture theme_skyline theme_atmosphere theme_shopping_clothes theme_nightlife theme_musicals theme_people_watching theme_ambiance theme_tourism theme_convenient_public_transport theme_fine_art_museums synonym_destfinder_themes_art theme_culturally_diverse_food theme_monuments theme_luxury_brand_shopping theme_friendly_people theme_scenery synonym_destfinder_themes_history
london 51.500999450683594 -0.1263429969549179 30 theme_shopping theme_museums synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture synonym_destfinder_themes_history theme_theatre theme_monuments theme_parks synonym_destfinder_themes_entertainment theme_city_trip synonym_destfinder_themes_restaurants theme_food theme_city_walks theme_convenient_public_transport theme_architecture theme_atmosphere theme_walking theme_shopping_clothes theme_pub_hopping theme_tourism theme_musicals theme_ambiance theme_markets theme_nightlife theme_street_markets theme_culturally_diverse_food synonym_destfinder_themes_art theme_friendly_people theme_luxury_brand_shopping theme_ancient_landmarks
berlin 52.516214284031705 13.376817321404815 30 synonym_destfinder_themes_history theme_museums synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture theme_shopping theme_city_trip theme_monuments theme_architecture theme_food theme_nightlife theme_city_walks theme_convenient_public_transport theme_atmosphere synonym_destfinder_themes_restaurants theme_walking theme_ambiance theme_friendly_people theme_parks theme_beer synonym_destfinder_themes_art synonym_destfinder_themes_cafes theme_alternative theme_tourism theme_bar_hopping theme_shopping_clothes synonym_destfinder_themes_entertainment theme_culturally_diverse_food theme_old_town theme_zoo theme_fine_art_museums
amsterdam 52.37289810180664 4.89300012588501 30 theme_museums theme_city_walks synonym_destfinder_themes_sightseeing theme_architecture theme_walking synonym_destfinder_themes_culture theme_nightlife theme_shopping theme_cycling theme_food theme_atmosphere theme_ambiance theme_city_trip theme_friendly_people synonym_destfinder_themes_cafes theme_old_town theme_convenient_public_transport theme_fine_art_museums synonym_destfinder_themes_history theme_bar_hopping synonym_destfinder_themes_art synonym_destfinder_themes_entertainment synonym_destfinder_themes_relax theme_scenery synonym_destfinder_themes_restaurants theme_tourism theme_boating theme_beer theme_parks theme_flowers
dubai 25.19517486731745 55.272677801549435 30 theme_shopping theme_luxury_brand_shopping synonym_destfinder_themes_relax theme_beach theme_food theme_shopping_clothes synonym_destfinder_themes_sightseeing theme_business theme_architecture theme_desert synonym_destfinder_themes_entertainment synonym_destfinder_themes_restaurants theme_tourism theme_clean_streets theme_fam_friendly theme_markets theme_nightlife theme_city_trip theme_fine_dining theme_beach_walks theme_friendly_people theme_city_walks theme_fountain theme_sand_beaches theme_theme_parks theme_convenient_public_transport theme_culturally_diverse_food theme_sunny theme_gourmet theme_atmosphere
lasvegas 36.11899948120117 -115.16799926757812 30 synonym_destfinder_themes_entertainment theme_gambling theme_nightlife theme_shopping theme_food synonym_destfinder_themes_sightseeing theme_atmosphere synonym_destfinder_themes_restaurants theme_people_watching theme_city_walks theme_walking theme_bar_hopping theme_warm_weather synonym_destfinder_themes_relax theme_ambiance theme_luxury_brand_shopping theme_live_music theme_clubbing theme_outlets theme_swimming_pools theme_fine_dining theme_architecture theme_shopping_clothes theme_adventure theme_city_trip theme_gourmet theme_culturally_diverse_food theme_nature theme_museums theme_hot_weather
venice 45.43389129638672 12.338504791259766 30 review_destination_themes_romantic theme_architecture synonym_destfinder_themes_sightseeing synonym_destfinder_themes_history synonym_destfinder_themes_culture theme_museums theme_food theme_city_walks theme_walking theme_atmosphere synonym_destfinder_themes_art theme_ambiance theme_scenery theme_old_town theme_photography theme_monuments theme_churches theme_ancient_landmarks theme_boating theme_promenade theme_city_trip theme_shopping theme_tourism synonym_destfinder_themes_restaurants synonym_destfinder_themes_relax theme_friendly_people theme_local_food theme_fine_art_museums theme_seafood theme_carnival
madrid 40.41669845581055 -3.7034199237823486 30 theme_museums synonym_destfinder_themes_culture theme_shopping theme_food theme_architecture theme_monuments theme_tapas theme_parks theme_nightlife theme_city_walks synonym_destfinder_themes_sightseeing theme_city_trip theme_gourmet theme_ambiance theme_fine_art_museums theme_walking theme_atmosphere synonym_destfinder_themes_restaurants synonym_destfinder_themes_history theme_friendly_people theme_old_town synonym_destfinder_themes_art synonym_destfinder_themes_entertainment theme_convenient_public_transport theme_tourism theme_bar_hopping theme_theatre theme_local_food theme_shopping_clothes theme_art_galleries
shanghai 31.229421319298854 121.47630288032815 30 theme_shopping synonym_destfinder_themes_sightseeing theme_food theme_architecture theme_business theme_city_trip theme_nightlife theme_city_walks synonym_destfinder_themes_culture theme_skyline theme_museums theme_convenient_public_transport synonym_destfinder_themes_restaurants theme_culturally_diverse_food theme_tourism theme_atmosphere theme_walking synonym_destfinder_themes_history theme_streetfood theme_ambiance theme_local_food theme_shopping_clothes theme_fine_dining theme_bar_hopping theme_scenery theme_markets theme_gourmet theme_clean_streets theme_people_watching theme_dim_sum
istanbul 41.00817124709046 28.974445598287275 30 synonym_destfinder_themes_history theme_shopping theme_food synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture theme_museums theme_old_town theme_monuments theme_architecture theme_friendly_people theme_nightlife theme_city_walks theme_ancient_landmarks theme_atmosphere theme_local_food theme_ambiance theme_city_trip theme_scenery theme_markets theme_tourism synonym_destfinder_themes_restaurants theme_shopping_clothes theme_walking theme_traditional_food theme_street_markets theme_culturally_diverse_food theme_gourmet theme_convenient_public_transport theme_streetfood theme_seaside
munich 48.137298583984375 11.575599670410156 30 theme_beer theme_museums theme_shopping synonym_destfinder_themes_sightseeing theme_food synonym_destfinder_themes_culture theme_architecture theme_city_walks theme_oktoberfest theme_old_town theme_city_trip theme_convenient_public_transport synonym_destfinder_themes_history theme_atmosphere theme_parks theme_walking theme_ambiance theme_friendly_people synonym_destfinder_themes_restaurants theme_local_food theme_traditional_food theme_markets theme_monuments theme_clean_streets theme_shopping_clothes theme_castles theme_churches theme_christmas_markets theme_football theme_scenery
benidorm 38.53659948434981 -0.13268314982269658 30 theme_beach theme_nightlife synonym_destfinder_themes_entertainment theme_sunny theme_shopping theme_beach_walks theme_atmosphere theme_sand_beaches theme_warm_weather theme_ambiance theme_bar_hopping synonym_destfinder_themes_relax synonym_destfinder_themes_restaurants theme_food theme_sun_bathing theme_walking review_destination_themes_budget theme_promenade theme_old_town theme_friendly_people theme_hot_weather theme_tapas theme_pub_hopping theme_coastal_walks theme_beer theme_fam_friendly theme_seaside theme_tourism theme_people_watching synonym_destfinder_themes_cafes
bangkok 13.755838394165039 100.5056381225586 30 theme_shopping theme_food theme_temples theme_nightlife synonym_destfinder_themes_sightseeing theme_streetfood synonym_destfinder_themes_culture theme_shopping_clothes theme_markets theme_street_markets theme_friendly_people theme_night_markets theme_local_food review_destination_themes_budget theme_city_trip theme_tourism synonym_destfinder_themes_restaurants theme_atmosphere synonym_destfinder_themes_relax theme_city_walks theme_culturally_diverse_food synonym_destfinder_themes_entertainment theme_convenient_public_transport theme_ambiance theme_bar_hopping theme_monuments theme_ancient_landmarks theme_health_spas theme_shopping_accessories theme_gourmet
hamburg 53.54999923706055 10 30 theme_harbour synonym_destfinder_themes_sightseeing theme_musicals theme_shopping theme_fish_markets theme_city_walks theme_museums theme_city_trip theme_atmosphere theme_convenient_public_transport theme_old_town theme_food synonym_destfinder_themes_restaurants theme_nightlife theme_architecture theme_walking synonym_destfinder_themes_culture theme_friendly_people theme_ambiance synonym_destfinder_themes_history theme_bar_hopping theme_seafood theme_parks theme_shopping_clothes theme_theatre theme_christmas_markets synonym_destfinder_themes_relax theme_live_music theme_beer theme_markets
toulouse 43.60430145263672 1.440750002861023 30 theme_architecture theme_shopping theme_gourmet theme_museums theme_food theme_city_walks theme_old_town theme_city_trip theme_ambiance synonym_destfinder_themes_restaurants synonym_destfinder_themes_culture synonym_destfinder_themes_sightseeing theme_atmosphere theme_monuments theme_walking synonym_destfinder_themes_history theme_friendly_people theme_promenade theme_tourism theme_convenient_public_transport synonym_destfinder_themes_cafes theme_bar_hopping theme_ancient_landmarks theme_scenery theme_churches theme_markets theme_cathedral theme_local_food theme_parks theme_nightlife
lyon 45.757768142204675 4.832203753940121 30 theme_old_town theme_gourmet theme_food theme_shopping theme_museums theme_city_walks theme_architecture synonym_destfinder_themes_restaurants synonym_destfinder_themes_culture theme_walking theme_convenient_public_transport synonym_destfinder_themes_sightseeing theme_city_trip synonym_destfinder_themes_history theme_ambiance theme_monuments theme_promenade theme_local_food theme_parks theme_friendly_people theme_scenery theme_fine_dining theme_nightlife theme_wine theme_fine_art_museums theme_cathedral theme_atmosphere theme_churches theme_tourism theme_ancient_landmarks
florence 43.771427 11.254021 30 theme_museums synonym_destfinder_themes_art synonym_destfinder_themes_culture synonym_destfinder_themes_history theme_architecture theme_food theme_monuments theme_shopping theme_old_town theme_city_walks synonym_destfinder_themes_sightseeing theme_cathedral theme_churches theme_fine_art_museums theme_walking theme_art_galleries theme_ancient_landmarks theme_atmosphere theme_scenery theme_ambiance review_destination_themes_romantic synonym_destfinder_themes_restaurants theme_fine_dining theme_local_food theme_city_trip theme_friendly_people theme_wine theme_tourism theme_traditional_food theme_galleries
vienna 48.20854568481445 16.372804641723633 30 theme_museums synonym_destfinder_themes_culture theme_architecture synonym_destfinder_themes_sightseeing synonym_destfinder_themes_history theme_monuments theme_city_walks theme_food theme_shopping theme_old_town synonym_destfinder_themes_art theme_convenient_public_transport destination_finder_theme_opera theme_parks theme_city_trip synonym_destfinder_themes_cafes theme_atmosphere theme_live_music theme_ambiance theme_walking theme_fine_art_museums theme_classical_music theme_clean_streets theme_coffee synonym_destfinder_themes_restaurants theme_castles theme_churches theme_friendly_people review_destination_themes_romantic theme_theatre
marseille 43.298301696777344 5.3779802322387695 30 theme_harbour theme_museums synonym_destfinder_themes_culture theme_food theme_beach theme_city_walks theme_old_town theme_city_trip synonym_destfinder_themes_sightseeing theme_sunny theme_scenery theme_seaside theme_walking theme_promenade theme_ambiance theme_seafood theme_monuments theme_atmosphere theme_architecture synonym_destfinder_themes_history theme_warm_weather synonym_destfinder_themes_restaurants theme_shopping theme_tourism theme_hot_weather theme_friendly_people theme_coastal_walks theme_local_food theme_boating theme_cathedral
orlando 28.53529930114746 -81.38330078125 30 theme_theme_parks theme_shopping theme_universalstudios theme_disneyland theme_parks theme_fam_friendly theme_outlets synonym_destfinder_themes_entertainment synonym_destfinder_themes_restaurants theme_warm_weather theme_food synonym_destfinder_themes_relax theme_shopping_clothes theme_tourism theme_sunny theme_friendly_people synonym_destfinder_themes_sightseeing theme_adventure theme_swimming_pools synonym_destfinder_themes_tranquility theme_nightlife theme_luxury_brand_shopping theme_nature theme_golf theme_museums theme_hot_weather theme_fine_dining theme_beach theme_clean_streets theme_shopping_accessories
milan 45.464298248291016 9.188779830932617 30 theme_shopping theme_cathedral theme_luxury_brand_shopping theme_food theme_architecture theme_museums synonym_destfinder_themes_culture theme_shopping_clothes theme_city_walks synonym_destfinder_themes_sightseeing synonym_destfinder_themes_restaurants theme_convenient_public_transport theme_monuments theme_city_trip synonym_destfinder_themes_art theme_old_town theme_walking theme_ambiance theme_atmosphere synonym_destfinder_themes_history theme_design theme_fashion_bargains theme_churches theme_nightlife theme_tourism theme_friendly_people theme_local_food theme_gourmet theme_fine_dining theme_pizza
bordeaux 44.83781814575195 -0.5786597728729248 30 theme_architecture theme_wine theme_shopping theme_food theme_gourmet theme_city_walks theme_city_trip theme_old_town theme_monuments synonym_destfinder_themes_sightseeing synonym_destfinder_themes_restaurants synonym_destfinder_themes_history theme_walking synonym_destfinder_themes_culture theme_ambiance theme_atmosphere theme_convenient_public_transport theme_promenade theme_riverside_walks theme_museums theme_ancient_landmarks theme_scenery theme_tourism theme_cathedral theme_shopping_wine review_destination_themes_romantic theme_parks theme_unesco synonym_destfinder_themes_cafes theme_vineyards
dublin 53.34976 -6.26027 30 theme_pub_hopping theme_friendly_people theme_live_music theme_shopping synonym_destfinder_themes_sightseeing theme_nightlife synonym_destfinder_themes_history theme_beer theme_atmosphere synonym_destfinder_themes_culture theme_food theme_bar_hopping theme_museums theme_city_trip theme_city_walks synonym_destfinder_themes_restaurants theme_ambiance synonym_destfinder_themes_entertainment theme_walking theme_convenient_public_transport theme_architecture theme_monuments theme_tourism theme_parks theme_street_musicians theme_shopping_clothes theme_tours theme_scenery theme_old_town theme_churches
singapore 1.29045 103.85204 30 theme_shopping theme_clean_streets theme_food synonym_destfinder_themes_sightseeing theme_city_trip theme_culturally_diverse_food theme_convenient_public_transport theme_universalstudios theme_zoo theme_city_walks theme_botanical_garden theme_friendly_people theme_architecture theme_luxury_brand_shopping theme_tourism theme_atmosphere theme_parks theme_walking theme_skyline synonym_destfinder_themes_relax theme_local_food theme_chinatown theme_shopping_clothes theme_theme_parks synonym_destfinder_themes_restaurants theme_fam_friendly theme_streetfood theme_scenery theme_nightlife theme_ambiance
prague 50.087730407714844 14.421133041381836 30 theme_architecture theme_old_town synonym_destfinder_themes_sightseeing synonym_destfinder_themes_history theme_monuments theme_beer synonym_destfinder_themes_culture theme_city_walks theme_food review_destination_themes_romantic theme_museums theme_walking theme_ambiance theme_castles theme_atmosphere theme_city_trip synonym_destfinder_themes_restaurants theme_scenery theme_convenient_public_transport theme_ancient_landmarks theme_local_food theme_shopping theme_nightlife theme_cathedral theme_friendly_people theme_churches theme_traditional_food theme_tourism review_destination_themes_budget theme_pub_hopping
brussels 50.846706551167195 4.352471709207748 30 theme_chocolate theme_beer theme_architecture theme_museums synonym_destfinder_themes_sightseeing theme_food synonym_destfinder_themes_culture theme_shopping theme_city_walks theme_old_town theme_waffles theme_city_trip theme_monuments theme_walking synonym_destfinder_themes_restaurants theme_ambiance theme_atmosphere synonym_destfinder_themes_history theme_friendly_people theme_gourmet theme_bar_hopping theme_tourism theme_parks synonym_destfinder_themes_cafes theme_convenient_public_transport theme_nightlife theme_fine_art_museums synonym_destfinder_themes_art theme_ancient_landmarks theme_markets
marrakech 31.628209631848723 -8.000632433017927 30 theme_souks synonym_destfinder_themes_culture theme_food theme_markets theme_shopping synonym_destfinder_themes_sightseeing theme_friendly_people theme_sunny theme_atmosphere theme_ambiance theme_old_town theme_traditional_food theme_local_food theme_street_markets theme_city_walks theme_architecture theme_warm_weather theme_hot_weather synonym_destfinder_themes_history synonym_destfinder_themes_relax theme_walking theme_scenery synonym_destfinder_themes_excursions theme_ancient_landmarks theme_monuments theme_streetfood theme_city_trip synonym_destfinder_themes_restaurants theme_people_watching theme_culturally_diverse_food
hongkong 22.282697459431052 114.15827108983649 30 theme_shopping theme_food synonym_destfinder_themes_sightseeing theme_luxury_brand_shopping theme_shopping_clothes theme_gourmet theme_disneyland theme_convenient_public_transport theme_city_trip theme_city_walks theme_dim_sum theme_local_food theme_nightlife theme_culturally_diverse_food theme_scenery theme_skyline theme_streetfood theme_street_markets synonym_destfinder_themes_restaurants theme_atmosphere synonym_destfinder_themes_culture theme_night_markets theme_markets theme_ambiance theme_business theme_friendly_people theme_shopping_electronics theme_architecture theme_theme_parks synonym_destfinder_themes_relax
nice 43.698079916262756 7.269624011514679 30 theme_beach theme_old_town theme_promenade theme_food synonym_destfinder_themes_restaurants theme_shopping synonym_destfinder_themes_relax theme_seaside theme_sunny theme_warm_weather theme_city_walks theme_scenery theme_beach_walks theme_walking theme_coastal_walks theme_atmosphere theme_ambiance synonym_destfinder_themes_sightseeing theme_city_trip theme_museums theme_architecture theme_markets theme_convenient_public_transport synonym_destfinder_themes_culture theme_friendly_people theme_seafood theme_pebble_beaches theme_sun_bathing theme_parks theme_gourmet
nantes 47.21670150756836 -1.5499999523162842 30 theme_castles synonym_destfinder_themes_culture theme_architecture theme_shopping theme_museums theme_city_walks theme_city_trip theme_old_town synonym_destfinder_themes_restaurants theme_ambiance theme_atmosphere theme_monuments synonym_destfinder_themes_history theme_promenade theme_walking theme_parks theme_cathedral theme_tourism synonym_destfinder_themes_sightseeing theme_friendly_people theme_convenient_public_transport theme_botanical_garden theme_bar_hopping theme_food theme_gourmet synonym_destfinder_themes_art synonym_destfinder_themes_tranquility theme_scenery theme_nightlife theme_clean_streets
lisbon 38.71383285522461 -9.139314651489258 30 theme_food theme_city_walks theme_old_town synonym_destfinder_themes_sightseeing theme_friendly_people theme_architecture synonym_destfinder_themes_culture synonym_destfinder_themes_history theme_monuments theme_museums theme_city_trip theme_atmosphere theme_ambiance theme_walking theme_local_food synonym_destfinder_themes_restaurants theme_convenient_public_transport theme_scenery theme_traditional_food theme_seafood theme_warm_weather theme_ancient_landmarks theme_castles theme_shopping theme_tourism theme_nightlife theme_gourmet theme_sunny theme_promenade synonym_destfinder_themes_cafes
montpellier 43.61080551147461 3.8766725063323975 30 theme_city_walks theme_old_town theme_architecture theme_shopping theme_beach theme_ambiance synonym_destfinder_themes_restaurants theme_city_trip theme_atmosphere theme_sunny theme_food theme_convenient_public_transport synonym_destfinder_themes_culture theme_warm_weather theme_promenade synonym_destfinder_themes_sightseeing synonym_destfinder_themes_cafes theme_walking theme_nightlife theme_bar_hopping theme_friendly_people synonym_destfinder_themes_history theme_sand_beaches theme_monuments synonym_destfinder_themes_relax synonym_destfinder_themes_tranquility theme_beach_walks theme_museums theme_wine theme_gourmet
sydney -33.87045669555664 151.20901489257812 30 synonym_destfinder_themes_sightseeing theme_shopping theme_harbour theme_food theme_beach synonym_destfinder_themes_restaurants synonym_destfinder_themes_entertainment destination_finder_theme_opera theme_scenery theme_city_walks theme_city_trip theme_convenient_public_transport theme_walking theme_atmosphere theme_nightlife theme_friendly_people theme_culturally_diverse_food synonym_destfinder_themes_cafes theme_botanical_garden theme_tourism theme_museums theme_parks theme_warm_weather synonym_destfinder_themes_relax theme_zoo theme_sand_beaches theme_shopping_clothes synonym_destfinder_themes_culture theme_beach_walks theme_theatre
valencia 39.46979904174805 -0.37654200196266174 30 theme_old_town theme_beach theme_architecture theme_food synonym_destfinder_themes_culture theme_museums theme_shopping theme_city_walks theme_atmosphere synonym_destfinder_themes_sightseeing theme_paella theme_warm_weather theme_city_trip theme_walking theme_aquarium theme_friendly_people theme_parks theme_sunny theme_ambiance theme_tapas synonym_destfinder_themes_restaurants theme_monuments theme_beach_walks theme_sand_beaches theme_markets theme_cathedral theme_local_food synonym_destfinder_themes_relax synonym_destfinder_themes_history theme_cycling
budapest 47.498416900634766 19.04033660888672 30 theme_architecture synonym_destfinder_themes_sightseeing theme_monuments synonym_destfinder_themes_history theme_food synonym_destfinder_themes_culture theme_health_spas theme_museums theme_nightlife theme_city_walks theme_city_trip theme_old_town theme_walking theme_hot_springs theme_atmosphere theme_ambiance theme_scenery synonym_destfinder_themes_restaurants theme_convenient_public_transport theme_friendly_people review_destination_themes_budget theme_local_food theme_castles synonym_destfinder_themes_relax review_destination_themes_romantic theme_shopping synonym_destfinder_themes_cafes theme_bar_hopping theme_traditional_food theme_ancient_landmarks
lille 50.636845393481735 3.063454139046371 30 theme_old_town theme_shopping theme_architecture theme_food theme_museums synonym_destfinder_themes_restaurants theme_city_walks theme_ambiance synonym_destfinder_themes_culture theme_city_trip theme_gourmet theme_friendly_people theme_atmosphere theme_walking synonym_destfinder_themes_sightseeing theme_beer theme_fine_art_museums synonym_destfinder_themes_cafes synonym_destfinder_themes_history theme_local_food theme_monuments theme_bar_hopping theme_promenade theme_nightlife theme_shopping_clothes theme_fashion_bargains synonym_destfinder_themes_relax theme_parks theme_shopping_food theme_scenery
chicago 41.88209915161133 -87.62429809570312 30 theme_architecture theme_museums theme_shopping theme_food synonym_destfinder_themes_sightseeing synonym_destfinder_themes_restaurants theme_city_walks theme_parks theme_skyline theme_walking theme_city_trip theme_friendly_people synonym_destfinder_themes_culture synonym_destfinder_themes_art theme_pizza theme_nightlife theme_scenery synonym_destfinder_themes_entertainment theme_fine_art_museums theme_live_music theme_shopping_clothes theme_culturally_diverse_food theme_aquarium theme_sport theme_theatre theme_gourmet theme_lakes theme_clean_streets theme_fine_dining theme_bar_hopping
strasbourg 48.58250045776367 7.744160175323486 30 theme_old_town theme_cathedral theme_architecture theme_food theme_gourmet theme_city_walks synonym_destfinder_themes_history theme_shopping synonym_destfinder_themes_sightseeing theme_city_trip theme_christmas_markets theme_walking synonym_destfinder_themes_culture theme_museums theme_atmosphere theme_ambiance synonym_destfinder_themes_restaurants theme_monuments theme_promenade theme_local_food review_destination_themes_romantic theme_friendly_people theme_scenery theme_convenient_public_transport theme_wine theme_tourism theme_traditional_food theme_churches synonym_destfinder_themes_cafes theme_boating
stockholm 59.33241653442383 18.065214157104492 30 theme_museums theme_old_town theme_shopping synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture theme_architecture theme_food theme_city_walks theme_walking theme_city_trip theme_scenery synonym_destfinder_themes_restaurants theme_convenient_public_transport theme_friendly_people theme_ambiance synonym_destfinder_themes_history theme_atmosphere theme_parks theme_monuments theme_nature synonym_destfinder_themes_cafes theme_clean_streets theme_boating synonym_destfinder_themes_relax theme_design theme_fine_dining theme_shopping_clothes synonym_destfinder_themes_tranquility theme_nightlife theme_bar_hopping
seville 37.38863333326453 -5.9955524504403 30 theme_monuments theme_tapas synonym_destfinder_themes_culture theme_cathedral theme_architecture synonym_destfinder_themes_history theme_food theme_old_town theme_city_walks theme_atmosphere synonym_destfinder_themes_sightseeing theme_friendly_people theme_ambiance theme_walking theme_flamenco theme_parks theme_ancient_landmarks theme_city_trip theme_sunny theme_warm_weather theme_bar_hopping theme_tourism theme_museums synonym_destfinder_themes_restaurants theme_nightlife theme_local_food theme_churches synonym_destfinder_themes_art theme_shopping theme_hot_weather
boston 42.3588981628418 -71.05780029296875 30 synonym_destfinder_themes_history synonym_destfinder_themes_sightseeing theme_food theme_museums theme_shopping theme_city_walks theme_walking theme_architecture synonym_destfinder_themes_culture theme_seafood synonym_destfinder_themes_restaurants theme_monuments theme_friendly_people theme_city_trip theme_parks theme_harbour theme_atmosphere theme_old_town theme_convenient_public_transport theme_tours theme_sport theme_scenery theme_clean_streets theme_ambiance theme_pub_hopping theme_culturally_diverse_food theme_tourism theme_bar_hopping synonym_destfinder_themes_tranquility theme_shopping_clothes
copenhagen 55.67878723144531 12.579431533813477 30 synonym_destfinder_themes_sightseeing theme_architecture theme_shopping synonym_destfinder_themes_culture theme_food theme_friendly_people theme_museums theme_city_walks theme_city_trip theme_atmosphere theme_walking theme_ambiance theme_cycling theme_harbour theme_design synonym_destfinder_themes_restaurants theme_parks theme_old_town theme_convenient_public_transport synonym_destfinder_themes_history synonym_destfinder_themes_cafes synonym_destfinder_themes_relax theme_clean_streets theme_monuments theme_castles theme_scenery theme_beer theme_carnival synonym_destfinder_themes_tranquility theme_bar_hopping
salou 41.074798583984375 1.1427500247955322 30 theme_beach theme_theme_parks theme_beach_walks theme_sand_beaches theme_nightlife theme_sunny theme_fam_friendly theme_shopping theme_seaside theme_ambiance theme_hot_weather theme_sun_bathing theme_atmosphere theme_walking theme_warm_weather synonym_destfinder_themes_entertainment synonym_destfinder_themes_restaurants theme_promenade theme_beaches_for_kids theme_bar_hopping synonym_destfinder_themes_relax theme_friendly_people t_generic_photo_tag_outdoors_1 theme_convenient_public_transport theme_city_walks theme_tourism theme_food theme_swimming_pools theme_clean_streets synonym_destfinder_themes_tranquility
sanfrancisco 37.787804 -122.407503 30 synonym_destfinder_themes_sightseeing theme_food theme_scenery theme_city_trip theme_shopping synonym_destfinder_themes_restaurants theme_architecture theme_city_walks theme_walking theme_atmosphere theme_harbour theme_seafood synonym_destfinder_themes_culture theme_tourism theme_friendly_people theme_parks theme_convenient_public_transport theme_culturally_diverse_food theme_ambiance theme_chinatown synonym_destfinder_themes_history theme_museums theme_people_watching theme_cycling theme_nature synonym_destfinder_themes_entertainment synonym_destfinder_themes_relax theme_nightlife theme_shopping_clothes theme_gourmet
edinburgh 55.94835 -3.19312 30 synonym_destfinder_themes_history synonym_destfinder_themes_sightseeing theme_castles theme_architecture synonym_destfinder_themes_culture theme_shopping theme_museums theme_food theme_old_town theme_friendly_people theme_pub_hopping theme_scenery theme_city_walks theme_monuments theme_atmosphere synonym_destfinder_themes_restaurants theme_city_trip theme_walking theme_ancient_landmarks theme_bar_hopping theme_ambiance theme_tourism theme_convenient_public_transport theme_nightlife theme_parks theme_tours synonym_destfinder_themes_entertainment synonym_destfinder_themes_relax theme_nature theme_shopping_clothes
vancouver 49.2824122332154 -123.12119346452164 30 theme_scenery synonym_destfinder_themes_sightseeing theme_food theme_nature theme_shopping theme_parks theme_walking theme_friendly_people theme_city_walks synonym_destfinder_themes_restaurants theme_mountains theme_city_trip theme_culturally_diverse_food theme_nature_walks t_generic_photo_tag_outdoors_1 theme_cycling synonym_destfinder_themes_relax theme_beach theme_aquarium theme_seafood theme_hiking synonym_destfinder_themes_culture theme_nightlife theme_gourmet theme_museums theme_shopping_clothes theme_whales theme_live_music theme_convenient_public_transport theme_clean_streets
albufeira 37.088600158691406 -8.25082015991211 30 theme_beach theme_sand_beaches theme_nightlife synonym_destfinder_themes_relax theme_food theme_sunny theme_beach_walks synonym_destfinder_themes_restaurants theme_sun_bathing theme_bar_hopping theme_friendly_people theme_scenery theme_warm_weather theme_old_town theme_seaside theme_hot_weather theme_ambiance theme_atmosphere theme_seafood theme_local_food theme_fam_friendly theme_coastal_walks synonym_destfinder_themes_entertainment synonym_destfinder_themes_cafes theme_live_music theme_tourism theme_pub_hopping theme_traditional_food theme_beaches_for_kids theme_swimming_pools
rennes 48.111358642578125 -1.6792774200439453 30 theme_old_town theme_architecture synonym_destfinder_themes_restaurants theme_city_trip theme_shopping theme_city_walks theme_ambiance theme_atmosphere synonym_destfinder_themes_history synonym_destfinder_themes_culture theme_friendly_people theme_walking synonym_destfinder_themes_sightseeing theme_local_food theme_monuments theme_parks theme_nightlife synonym_destfinder_themes_tranquility theme_food theme_bar_hopping theme_markets theme_scenery theme_gourmet theme_museums theme_convenient_public_transport theme_tourism theme_clean_streets theme_promenade theme_fine_art_museums theme_cathedral
bruges 51.20891160446596 3.2242740271613 30 theme_architecture theme_chocolate theme_beer synonym_destfinder_themes_history theme_museums theme_old_town theme_city_walks synonym_destfinder_themes_sightseeing review_destination_themes_romantic theme_walking theme_atmosphere theme_food theme_ambiance synonym_destfinder_themes_culture theme_scenery theme_shopping theme_city_trip theme_monuments synonym_destfinder_themes_restaurants synonym_destfinder_themes_relax theme_friendly_people synonym_destfinder_themes_tranquility theme_promenade theme_churches theme_waffles theme_gourmet theme_cycling theme_nightlife theme_ancient_landmarks synonym_destfinder_themes_art
melbourne -37.81422 144.96316 30 theme_shopping theme_food synonym_destfinder_themes_restaurants synonym_destfinder_themes_entertainment synonym_destfinder_themes_culture theme_shopping_clothes theme_sport theme_convenient_public_transport synonym_destfinder_themes_cafes synonym_destfinder_themes_sightseeing theme_coffee theme_culturally_diverse_food theme_city_walks theme_atmosphere theme_markets theme_theatre theme_city_trip theme_friendly_people theme_museums synonym_destfinder_themes_art theme_walking theme_nightlife theme_architecture theme_parks synonym_destfinder_themes_relax theme_bar_hopping theme_gourmet theme_fine_dining theme_botanical_garden theme_live_music
seattle 47.60639953613281 -122.33100128173828 30 synonym_destfinder_themes_sightseeing theme_markets theme_food theme_seafood theme_shopping theme_museums theme_scenery synonym_destfinder_themes_restaurants theme_coffee theme_walking theme_city_walks theme_friendly_people theme_city_trip theme_atmosphere theme_fish_markets theme_harbour theme_nature theme_tourism theme_ambiance synonym_destfinder_themes_relax theme_mountains theme_convenient_public_transport theme_gourmet synonym_destfinder_themes_culture theme_culturally_diverse_food theme_people_watching theme_parks synonym_destfinder_themes_art theme_aquarium theme_beer
losangeles 34.05220031738281 -118.24299621582031 30 theme_beach theme_universalstudios theme_shopping synonym_destfinder_themes_sightseeing theme_food theme_museums theme_warm_weather theme_beach_walks synonym_destfinder_themes_entertainment synonym_destfinder_themes_restaurants theme_sunny theme_theme_parks theme_sand_beaches theme_city_walks theme_city_trip theme_disneyland theme_tourism theme_nightlife theme_friendly_people theme_shopping_clothes theme_scenery theme_people_watching theme_luxury_brand_shopping synonym_destfinder_themes_relax theme_culturally_diverse_food synonym_destfinder_themes_culture theme_bar_hopping theme_live_music theme_nature theme_gourmet
washington 38.90134279335418 -77.03654014254425 30 theme_museums theme_monuments synonym_destfinder_themes_history synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture theme_architecture theme_walking theme_city_walks synonym_destfinder_themes_restaurants theme_food theme_parks theme_fine_art_museums theme_clean_streets theme_city_trip theme_tourism theme_art_galleries theme_convenient_public_transport theme_scenery theme_atmosphere theme_friendly_people theme_fam_friendly theme_galleries theme_ancient_landmarks theme_tours theme_old_town theme_ambiance theme_culturally_diverse_food synonym_destfinder_themes_relax theme_shopping synonym_destfinder_themes_art
tokyo 35.68596004617712 139.72951806417768 30 theme_shopping theme_food synonym_destfinder_themes_sightseeing theme_convenient_public_transport synonym_destfinder_themes_culture theme_friendly_people theme_temples theme_clean_streets theme_city_walks theme_city_trip theme_local_food theme_atmosphere synonym_destfinder_themes_restaurants theme_sushi theme_parks theme_shopping_clothes theme_gourmet theme_ambiance theme_shopping_electronics theme_architecture theme_scenery theme_museums theme_people_watching theme_shopping_food theme_nightlife theme_disneyland synonym_destfinder_themes_entertainment theme_culturally_diverse_food theme_fish_markets synonym_destfinder_themes_history
cologne 50.94070053100586 6.957940101623535 30 theme_cathedral theme_shopping theme_old_town synonym_destfinder_themes_sightseeing theme_museums theme_christmas_markets theme_city_walks theme_beer theme_city_trip theme_food theme_atmosphere synonym_destfinder_themes_restaurants theme_friendly_people synonym_destfinder_themes_culture theme_nightlife theme_walking synonym_destfinder_themes_history theme_churches theme_chocolate theme_ambiance theme_bar_hopping theme_shopping_clothes theme_architecture theme_carnival theme_monuments theme_markets theme_live_music theme_zoo theme_gourmet theme_business
myrtlebeach 33.69522413323808 -78.87633167854801 30 theme_beach synonym_destfinder_themes_relax theme_beach_walks theme_fam_friendly theme_shopping theme_food synonym_destfinder_themes_restaurants synonym_destfinder_themes_entertainment theme_seafood theme_warm_weather theme_sunny theme_swimming_pools theme_scenery theme_sand_beaches theme_beaches_for_kids synonym_destfinder_themes_sightseeing theme_sun_bathing theme_atmosphere theme_aquarium theme_friendly_people theme_adventure theme_nightlife theme_shopping_accessories review_destination_themes_romantic synonym_destfinder_themes_tranquility theme_shopping_clothes theme_golf theme_museums theme_fishing theme_nature
toronto 43.652000427246094 -79.38196563720703 30 theme_shopping synonym_destfinder_themes_sightseeing synonym_destfinder_themes_restaurants theme_food theme_museums synonym_destfinder_themes_entertainment theme_city_walks theme_city_trip theme_friendly_people theme_walking theme_aquarium theme_convenient_public_transport theme_culturally_diverse_food theme_nightlife synonym_destfinder_themes_culture theme_theatre theme_sport theme_shopping_clothes theme_architecture theme_bar_hopping theme_live_music theme_fine_dining synonym_destfinder_themes_art theme_nature theme_business theme_tourism theme_markets theme_gourmet theme_atmosphere theme_clean_streets
geneva 46.20794677734375 6.145799160003662 30 theme_lakes theme_old_town theme_scenery theme_shopping theme_museums theme_city_walks theme_convenient_public_transport synonym_destfinder_themes_sightseeing theme_city_trip theme_walking theme_luxury_brand_shopping theme_clean_streets synonym_destfinder_themes_relax synonym_destfinder_themes_tranquility theme_chocolate theme_promenade theme_business theme_food theme_nature theme_atmosphere theme_ambiance theme_mountains theme_clean_air theme_fountain theme_architecture theme_parks theme_boating synonym_destfinder_themes_history synonym_destfinder_themes_restaurants theme_tourism
antalya 36.89133776083974 30.70346190230339 30 theme_beach theme_old_town synonym_destfinder_themes_relax theme_food theme_shopping theme_seaside theme_scenery theme_sunny theme_warm_weather theme_nature theme_beach_walks theme_waterfalls theme_coastal_walks theme_friendly_people synonym_destfinder_themes_history theme_city_walks theme_harbour theme_museums synonym_destfinder_themes_culture theme_ancient_landmarks synonym_destfinder_themes_sightseeing theme_city_trip theme_mountains theme_pebble_beaches theme_aquarium theme_monuments theme_sun_bathing theme_sand_beaches theme_wild_swimming theme_ambiance
miami 25.772224108577486 -80.19258060492575 30 theme_shopping theme_beach theme_nightlife theme_sand_beaches theme_food theme_warm_weather synonym_destfinder_themes_restaurants theme_sunny theme_beach_walks theme_tourism theme_shopping_clothes synonym_destfinder_themes_relax synonym_destfinder_themes_entertainment synonym_destfinder_themes_sightseeing theme_outlets theme_walking theme_friendly_people theme_ambiance theme_city_trip theme_promenade theme_bar_hopping theme_luxury_brand_shopping theme_culturally_diverse_food theme_fine_dining synonym_destfinder_themes_culture theme_nature theme_business theme_gourmet theme_museums theme_hot_weather
montral 45.50990652346541 -73.56745646764466 30 synonym_destfinder_themes_restaurants theme_food synonym_destfinder_themes_culture theme_shopping theme_museums theme_old_town theme_city_walks synonym_destfinder_themes_sightseeing theme_walking theme_nightlife theme_friendly_people theme_atmosphere theme_architecture theme_city_trip theme_ambiance synonym_destfinder_themes_history synonym_destfinder_themes_entertainment theme_parks theme_culturally_diverse_food theme_bar_hopping theme_live_music theme_harbour synonym_destfinder_themes_art theme_gourmet theme_botanical_garden theme_fine_art_museums theme_shopping_clothes theme_scenery theme_nature theme_jazz
miamibeach 25.790300369262695 -80.13030242919922 30 theme_beach theme_shopping theme_nightlife theme_beach_walks synonym_destfinder_themes_relax theme_food theme_sand_beaches synonym_destfinder_themes_restaurants theme_sunny theme_warm_weather theme_sun_bathing theme_atmosphere theme_bar_hopping synonym_destfinder_themes_entertainment theme_hot_weather theme_walking theme_people_watching theme_ambiance theme_friendly_people theme_shopping_clothes theme_clubbing theme_city_walks synonym_destfinder_themes_sightseeing theme_promenade t_generic_photo_tag_outdoors_1 theme_architecture theme_culturally_diverse_food theme_fine_dining theme_city_trip theme_gourmet
keywest 24.55121636083534 -81.7992203067115 30 theme_sunsets theme_nightlife synonym_destfinder_themes_relax theme_food theme_beach theme_atmosphere theme_bar_hopping theme_warm_weather synonym_destfinder_themes_restaurants theme_walking theme_ambiance theme_friendly_people synonym_destfinder_themes_sightseeing synonym_destfinder_themes_history theme_sunny theme_people_watching theme_live_music theme_scenery theme_seafood theme_water_sports theme_shopping theme_snorkeling theme_architecture theme_fishing theme_museums theme_diving theme_nature theme_boating synonym_destfinder_themes_entertainment theme_cycling
granada 37.17566649124251 -3.5974322835227213 30 theme_monuments synonym_destfinder_themes_history theme_tapas synonym_destfinder_themes_culture synonym_destfinder_themes_sightseeing theme_food theme_old_town theme_city_walks theme_atmosphere theme_architecture theme_ancient_landmarks theme_ambiance theme_walking theme_friendly_people theme_scenery theme_cathedral theme_unesco theme_tourism theme_bar_hopping theme_city_trip synonym_destfinder_themes_restaurants theme_flamenco theme_shopping theme_nightlife theme_museums synonym_destfinder_themes_art synonym_destfinder_themes_entertainment synonym_destfinder_themes_relax theme_gourmet theme_nature
tours 47.39005 0.68893 30 theme_old_town theme_castles theme_architecture synonym_destfinder_themes_history theme_city_walks theme_shopping theme_cathedral synonym_destfinder_themes_restaurants theme_ambiance theme_city_trip synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture theme_scenery theme_monuments theme_food theme_wine theme_gourmet theme_tours theme_museums theme_atmosphere theme_walking theme_churches theme_friendly_people synonym_destfinder_themes_tranquility theme_tourism theme_bar_hopping theme_ancient_landmarks synonym_destfinder_themes_relax theme_cycling theme_nightlife
aix-en-provence 43.52631378173828 5.44546365737915 30 theme_old_town synonym_destfinder_themes_culture theme_shopping theme_food theme_museums theme_city_walks theme_ambiance theme_architecture theme_atmosphere synonym_destfinder_themes_restaurants theme_markets theme_city_trip theme_walking synonym_destfinder_themes_history theme_fountain synonym_destfinder_themes_cafes synonym_destfinder_themes_sightseeing theme_street_markets theme_promenade theme_scenery synonym_destfinder_themes_relax theme_nightlife theme_friendly_people synonym_destfinder_themes_tranquility theme_fine_art_museums theme_monuments synonym_destfinder_themes_art theme_fine_dining theme_nature theme_gourmet
mlaga 36.714698791503906 -4.424739837646484 30 theme_beach theme_old_town theme_food theme_museums theme_tapas synonym_destfinder_themes_culture theme_shopping theme_city_walks theme_atmosphere theme_sunny theme_friendly_people theme_warm_weather theme_ambiance synonym_destfinder_themes_restaurants synonym_destfinder_themes_sightseeing theme_walking theme_city_trip theme_harbour theme_cathedral theme_beach_walks theme_seafood synonym_destfinder_themes_history theme_bar_hopping synonym_destfinder_themes_relax theme_nightlife theme_monuments theme_local_food theme_architecture theme_scenery synonym_destfinder_themes_art
sandiego 32.71246337890625 -117.1610336303711 30 theme_beach synonym_destfinder_themes_relax theme_warm_weather theme_zoo theme_food theme_shopping synonym_destfinder_themes_sightseeing theme_beach_walks synonym_destfinder_themes_restaurants theme_scenery theme_old_town theme_sand_beaches theme_harbour theme_friendly_people theme_fam_friendly theme_parks theme_museums theme_nightlife theme_sunny theme_sunsets theme_nature theme_seafood theme_city_trip theme_bar_hopping theme_theme_parks theme_culturally_diverse_food theme_fine_dining theme_surfing theme_beaches_for_kids theme_gourmet
moscow 55.752201080322266 37.6156005859375 30 synonym_destfinder_themes_sightseeing theme_museums theme_architecture synonym_destfinder_themes_history theme_parks synonym_destfinder_themes_culture theme_city_walks theme_walking theme_theatre theme_monuments theme_churches synonym_destfinder_themes_restaurants theme_fine_art_museums theme_ambiance theme_convenient_public_transport theme_shopping theme_old_town theme_nightlife synonym_destfinder_themes_entertainment theme_business theme_food synonym_destfinder_themes_art theme_temples theme_atmosphere synonym_destfinder_themes_excursions theme_clean_streets theme_city_trip theme_friendly_people theme_luxury_brand_shopping theme_zoo
riodejaneiro -22.90127099763644 -43.1790323741734 30 theme_beach theme_scenery synonym_destfinder_themes_sightseeing theme_beach_walks theme_nature theme_sand_beaches theme_nightlife theme_food theme_tourism theme_friendly_people theme_skyline theme_bar_hopping synonym_destfinder_themes_culture theme_sunny theme_walking theme_promenade t_generic_photo_tag_outdoors_1 theme_sunsets synonym_destfinder_themes_restaurants synonym_destfinder_themes_entertainment theme_hot_weather theme_city_trip theme_atmosphere theme_botanical_garden theme_city_walks theme_museums synonym_destfinder_themes_relax theme_ambiance theme_carnival theme_fine_dining
dijon 47.32176208496094 5.039809226989746 30 theme_old_town theme_architecture theme_gourmet theme_wine theme_museums theme_city_walks synonym_destfinder_themes_history theme_food theme_shopping synonym_destfinder_themes_restaurants theme_monuments theme_walking theme_city_trip theme_atmosphere theme_local_food theme_ancient_landmarks synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture synonym_destfinder_themes_tranquility theme_churches theme_friendly_people theme_ambiance theme_markets theme_fine_art_museums theme_scenery theme_shopping_wine theme_fine_dining theme_cathedral synonym_destfinder_themes_art theme_clean_streets
york 53.95830154418945 -1.0818099975585938 30 synonym_destfinder_themes_history theme_shopping synonym_destfinder_themes_sightseeing synonym_destfinder_themes_restaurants theme_museums theme_pub_hopping theme_food theme_city_walks theme_cathedral theme_architecture theme_old_town theme_atmosphere synonym_destfinder_themes_culture theme_friendly_people theme_monuments theme_walking theme_ancient_landmarks theme_bar_hopping synonym_destfinder_themes_relax theme_city_trip synonym_destfinder_themes_cafes theme_scenery theme_tourism theme_nightlife theme_shopping_clothes theme_horse_racing theme_fine_dining theme_high_tea review_destination_themes_romantic theme_castles
neworleans 29.951751708984375 -90.07681274414062 30 theme_food theme_live_music theme_nightlife synonym_destfinder_themes_history theme_jazz synonym_destfinder_themes_culture synonym_destfinder_themes_sightseeing theme_friendly_people theme_atmosphere theme_architecture synonym_destfinder_themes_restaurants theme_culturally_diverse_food theme_shopping synonym_destfinder_themes_entertainment theme_street_musicians theme_local_food theme_seafood theme_walking theme_people_watching theme_cocktails theme_bar_hopping theme_gourmet theme_tours synonym_destfinder_themes_relax theme_city_walks theme_scenery theme_tourism theme_ambiance theme_old_town theme_street_performers
reims 49.25779 4.03193 30 theme_cathedral theme_wine synonym_destfinder_themes_history theme_food theme_shopping theme_architecture theme_city_walks synonym_destfinder_themes_restaurants synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture theme_monuments theme_city_trip theme_shopping_wine theme_atmosphere theme_old_town theme_ancient_landmarks synonym_destfinder_themes_cafes theme_gourmet theme_friendly_people theme_churches theme_walking theme_scenery synonym_destfinder_themes_tranquility theme_museums theme_nightlife theme_christmas_markets theme_ambiance theme_vineyards synonym_destfinder_themes_relax theme_tourism
avignon 43.94900131225586 4.80750846862793 30 theme_old_town synonym_destfinder_themes_history theme_monuments synonym_destfinder_themes_culture theme_museums theme_city_walks theme_architecture synonym_destfinder_themes_sightseeing theme_ancient_landmarks theme_atmosphere theme_food theme_walking theme_scenery theme_ambiance synonym_destfinder_themes_restaurants theme_theatre theme_tourism synonym_destfinder_themes_art theme_castles theme_unesco theme_friendly_people theme_city_trip synonym_destfinder_themes_relax theme_shopping synonym_destfinder_themes_tranquility theme_wine theme_gourmet theme_nature theme_sunny theme_warm_weather
liverpool 53.4109001159668 -2.9781100749969482 30 theme_shopping theme_friendly_people theme_nightlife theme_museums synonym_destfinder_themes_culture synonym_destfinder_themes_restaurants synonym_destfinder_themes_sightseeing theme_pub_hopping theme_food theme_bar_hopping theme_atmosphere theme_football theme_live_music synonym_destfinder_themes_history theme_shopping_clothes theme_city_trip synonym_destfinder_themes_entertainment theme_architecture theme_cathedral synonym_destfinder_themes_relax theme_art_galleries theme_clubbing theme_monuments theme_theatre theme_luxury_brand_shopping synonym_destfinder_themes_art theme_nature theme_tourism theme_city_walks theme_harbour
dresden 51.05189895629883 13.741000175476074 30 theme_old_town synonym_destfinder_themes_sightseeing synonym_destfinder_themes_history theme_museums synonym_destfinder_themes_culture theme_architecture theme_city_walks theme_monuments theme_city_trip theme_churches theme_shopping destination_finder_theme_opera synonym_destfinder_themes_art theme_food synonym_destfinder_themes_restaurants theme_ambiance theme_christmas_markets theme_friendly_people theme_scenery theme_ancient_landmarks theme_fine_art_museums theme_castles theme_nature theme_markets theme_live_music theme_gourmet theme_walking theme_atmosphere review_destination_themes_romantic theme_galleries
cannes 43.552449026092255 7.0218729972839355 30 theme_beach theme_shopping synonym_destfinder_themes_restaurants theme_luxury_brand_shopping theme_food theme_seaside theme_sunny theme_ambiance theme_beach_walks theme_promenade synonym_destfinder_themes_relax theme_warm_weather theme_sand_beaches theme_city_walks theme_atmosphere theme_coastal_walks theme_walking theme_scenery theme_hot_weather theme_city_trip theme_harbour theme_sun_bathing synonym_destfinder_themes_tranquility theme_people_watching theme_architecture theme_shopping_clothes theme_old_town theme_nightlife review_destination_themes_romantic theme_seafood
grenoble 45.18248 5.72108 30 theme_mountains theme_scenery theme_downhill_skiing theme_shopping theme_museums theme_city_walks theme_old_town theme_city_trip synonym_destfinder_themes_restaurants theme_walking theme_mountain_walks theme_convenient_public_transport theme_ambiance synonym_destfinder_themes_sightseeing theme_nature synonym_destfinder_themes_tranquility synonym_destfinder_themes_history theme_architecture theme_hiking theme_friendly_people theme_food synonym_destfinder_themes_culture theme_gourmet theme_business theme_fine_art_museums theme_mountaineering t_generic_photo_tag_outdoors_1 theme_nature_walks synonym_destfinder_themes_relax theme_atmosphere
torremolinos 36.621567989483054 -4.497077282194368 30 theme_beach theme_beach_walks synonym_destfinder_themes_relax theme_food theme_shopping theme_sunny theme_sun_bathing synonym_destfinder_themes_restaurants theme_warm_weather theme_sand_beaches theme_atmosphere theme_promenade theme_friendly_people theme_hot_weather theme_seaside theme_coastal_walks theme_bar_hopping theme_fam_friendly theme_nightlife theme_local_food theme_ambiance review_destination_themes_budget theme_walking theme_tourism theme_seafood synonym_destfinder_themes_entertainment theme_convenient_public_transport theme_clean_streets theme_shopping_accessories theme_tapas
dubrovnik 42.64130783081055 18.108896255493164 30 theme_old_town synonym_destfinder_themes_history theme_scenery synonym_destfinder_themes_sightseeing theme_food theme_beach theme_city_walks theme_architecture synonym_destfinder_themes_culture theme_atmosphere theme_friendly_people theme_seaside theme_walking theme_unesco theme_sunny theme_seafood theme_ambiance theme_ancient_landmarks synonym_destfinder_themes_relax theme_monuments synonym_destfinder_themes_restaurants review_destination_themes_romantic theme_city_trip theme_nature theme_boating theme_castles theme_museums theme_wild_swimming theme_pebble_beaches theme_wine
blackpool 53.81669998168945 -3.049999952316284 30 synonym_destfinder_themes_entertainment theme_fam_friendly theme_nightlife theme_beach theme_shopping theme_promenade theme_pub_hopping theme_theme_parks theme_seaside theme_beach_walks theme_bar_hopping synonym_destfinder_themes_relax theme_food synonym_destfinder_themes_sightseeing theme_fish_and_chips theme_friendly_people theme_atmosphere theme_convenient_public_transport theme_walking review_destination_themes_budget synonym_destfinder_themes_restaurants theme_beaches_for_kids theme_sand_beaches theme_zoo theme_theatre theme_people_watching theme_tourism theme_coastal_walks theme_live_music theme_adventure
zrich 47.367149353027344 8.544272422790527 30 theme_old_town theme_lakes theme_shopping synonym_destfinder_themes_sightseeing theme_city_walks theme_museums theme_convenient_public_transport theme_scenery theme_walking theme_clean_streets theme_city_trip theme_chocolate synonym_destfinder_themes_culture theme_architecture theme_food synonym_destfinder_themes_restaurants theme_friendly_people theme_luxury_brand_shopping synonym_destfinder_themes_relax theme_nature theme_mountains synonym_destfinder_themes_history theme_nightlife theme_business theme_zoo theme_shopping_clothes theme_live_music theme_ambiance synonym_destfinder_themes_tranquility theme_atmosphere
honolulu 21.306900024414062 -157.85800170898438 30 theme_beach theme_shopping synonym_destfinder_themes_relax theme_food theme_surfing theme_warm_weather theme_sand_beaches theme_scenery synonym_destfinder_themes_sightseeing theme_snorkeling theme_beach_walks theme_friendly_people theme_sunsets theme_nature theme_sunny synonym_destfinder_themes_restaurants theme_tours theme_sun_bathing theme_walking theme_culturally_diverse_food theme_tropical theme_atmosphere theme_water_sports theme_beaches_for_kids theme_fam_friendly theme_seafood theme_nightlife theme_people_watching theme_shopping_clothes theme_hot_weather
annecy 45.899725939399346 6.127196090055804 30 theme_old_town theme_lakes theme_scenery theme_food theme_shopping theme_city_walks theme_walking theme_promenade review_destination_themes_romantic theme_mountains synonym_destfinder_themes_restaurants theme_ambiance theme_atmosphere synonym_destfinder_themes_sightseeing theme_nature synonym_destfinder_themes_relax t_generic_photo_tag_outdoors_1 synonym_destfinder_themes_tranquility synonym_destfinder_themes_history theme_city_trip theme_architecture theme_cycling theme_gourmet theme_hiking theme_castles theme_water_sports theme_markets theme_nature_walks theme_mountain_walks theme_friendly_people
pattayacentral 12.93402 100.8941 30 theme_nightlife theme_shopping theme_food synonym_destfinder_themes_relax theme_beach theme_bar_hopping synonym_destfinder_themes_entertainment theme_seafood theme_friendly_people synonym_destfinder_themes_restaurants theme_beach_walks theme_atmosphere theme_clubbing theme_streetfood theme_sunny theme_local_food theme_seaside review_destination_themes_budget theme_night_markets synonym_destfinder_themes_excursions theme_swimming_pools theme_sand_beaches theme_water_sports theme_ambiance theme_markets theme_nature theme_culturally_diverse_food synonym_destfinder_themes_sightseeing theme_shopping_clothes theme_gourmet
hurghada 27.25893211364746 33.811973571777344 30 synonym_destfinder_themes_relax theme_beach theme_diving theme_snorkeling theme_reef_diving theme_sunny theme_swimming_pools theme_warm_weather theme_fam_friendly theme_water_sports theme_nature theme_sun_bathing review_destination_themes_romantic theme_deep_sea_fishing theme_sand_beaches theme_kite_surf theme_beaches_for_kids theme_seaside theme_beach_walks theme_scenery theme_food theme_atmosphere review_destination_themes_budget theme_safari theme_seafood theme_wild_swimming theme_friendly_people theme_windsurfing theme_shopping theme_nightlife
angers 47.47399 -0.55156 30 theme_castles theme_old_town theme_architecture synonym_destfinder_themes_history theme_museums theme_city_walks theme_walking theme_city_trip synonym_destfinder_themes_tranquility theme_cathedral theme_ambiance synonym_destfinder_themes_restaurants synonym_destfinder_themes_sightseeing synonym_destfinder_themes_culture theme_monuments theme_clean_streets theme_friendly_people theme_food theme_shopping theme_scenery theme_wine theme_gourmet theme_fine_art_museums theme_ancient_landmarks theme_promenade theme_bar_hopping theme_tourism theme_parks theme_convenient_public_transport synonym_destfinder_themes_relax
clermont-ferrand 45.77746 3.08194 30 theme_volcanoes theme_old_town theme_cathedral synonym_destfinder_themes_restaurants theme_nature theme_city_walks theme_scenery theme_mountain_walks synonym_destfinder_themes_sightseeing theme_friendly_people synonym_destfinder_themes_tranquility theme_nature_walks theme_mountains theme_walking theme_architecture theme_gourmet theme_ambiance theme_local_food theme_city_trip theme_monuments synonym_destfinder_themes_history theme_hiking theme_shopping theme_food theme_rugby synonym_destfinder_themes_culture theme_museums theme_tourism theme_churches theme_clean_streets
playadelcarmen 20.627595901489258 -87.07479858398438 30 theme_beach theme_nightlife theme_food theme_shopping theme_diving synonym_destfinder_themes_relax synonym_destfinder_themes_restaurants theme_sand_beaches theme_snorkeling theme_beach_walks theme_sunny theme_walking t_generic_photo_tag_outdoors_1 theme_bar_hopping theme_atmosphere theme_wild_swimming theme_tourism synonym_destfinder_themes_entertainment theme_scenery synonym_destfinder_themes_excursions theme_water_sports theme_archeology theme_nature theme_maya_ruins theme_friendly_people theme_sun_bathing theme_clubbing synonym_destfinder_themes_sightseeing theme_local_food synonym_destfinder_themes_tranquility
marbella 36.51091 -4.88084 30 theme_beach synonym_destfinder_themes_relax theme_food theme_old_town theme_shopping synonym_destfinder_themes_restaurants theme_sunny theme_nightlife theme_beach_walks theme_warm_weather theme_atmosphere theme_sun_bathing theme_promenade theme_seaside theme_fine_dining theme_friendly_people theme_harbour theme_hot_weather theme_ambiance theme_bar_hopping theme_walking theme_clean_streets theme_seafood synonym_destfinder_themes_entertainment theme_clubbing theme_luxury_brand_shopping theme_scenery theme_tapas theme_people_watching theme_city_walks
rouen 49.44046 1.09397 30 theme_old_town theme_cathedral theme_architecture synonym_destfinder_themes_history theme_museums theme_city_walks synonym_destfinder_themes_restaurants theme_monuments theme_shopping theme_walking theme_churches synonym_destfinder_themes_sightseeing theme_ancient_landmarks theme_food synonym_destfinder_themes_culture theme_gourmet theme_city_trip theme_fine_art_museums synonym_destfinder_themes_art theme_scenery theme_ambiance theme_atmosphere theme_bar_hopping theme_friendly_people theme_tourism synonym_destfinder_themes_tranquility synonym_destfinder_themes_cafes theme_local_food theme_markets review_destination_themes_romantic
sharmelsheikh 27.915613174438477 34.328853607177734 30 synonym_destfinder_themes_relax theme_diving theme_beach theme_snorkeling theme_reef_diving theme_safari theme_nightlife theme_sunny theme_swimming_pools theme_water_sports theme_nature theme_beach_walks theme_fam_friendly theme_tours theme_wild_swimming theme_mountains synonym_destfinder_themes_entertainment theme_sun_bathing theme_friendly_people theme_adventure theme_atmosphere theme_sand_beaches theme_clean_streets review_destination_themes_romantic theme_scenery theme_seaside theme_sailing theme_culturally_diverse_food theme_food theme_seafood
rimini 44.05970001220703 12.569199562072754 30 theme_beach synonym_destfinder_themes_entertainment synonym_destfinder_themes_relax theme_fine_dining theme_food theme_sand_beaches theme_beach_walks theme_nightlife theme_seaside theme_shopping theme_friendly_people synonym_destfinder_themes_restaurants theme_walking theme_coastal_walks theme_old_town theme_seafood theme_sunny theme_promenade theme_beaches_for_kids theme_fam_friendly theme_sun_bathing theme_city_walks theme_atmosphere theme_ambiance theme_warm_weather theme_theme_parks t_generic_photo_tag_outdoors_1 theme_traditional_food theme_shopping_clothes theme_parks
atlanta 33.7489013671875 -84.38809967041016 30 theme_shopping theme_food theme_aquarium theme_nightlife theme_museums synonym_destfinder_themes_restaurants synonym_destfinder_themes_entertainment synonym_destfinder_themes_sightseeing theme_friendly_people synonym_destfinder_themes_relax theme_parks theme_city_trip theme_scenery theme_fam_friendly theme_culturally_diverse_food theme_fine_dining theme_clubbing theme_tourism synonym_destfinder_themes_culture theme_shopping_accessories theme_shopping_clothes synonym_destfinder_themes_history theme_live_music theme_zoo theme_sport theme_business theme_gourmet theme_convenient_public_transport theme_nature theme_atmosphere
frankfurt/main 50.11220169067383 8.68323040008545 30 theme_shopping theme_city_trip theme_business theme_museums theme_food theme_city_walks theme_old_town theme_skyline synonym_destfinder_themes_sightseeing theme_convenient_public_transport theme_architecture theme_walking synonym_destfinder_themes_restaurants synonym_destfinder_themes_culture theme_shopping_clothes theme_beer theme_friendly_people theme_nightlife theme_christmas_markets theme_markets synonym_destfinder_themes_history theme_luxury_brand_shopping theme_fine_art_museums synonym_destfinder_themes_relax destination_finder_theme_opera theme_zoo theme_nature theme_gourmet theme_live_music theme_cathedral
oceancity 38.33680725097656 -75.0840835571289 30 theme_beach theme_beach_walks synonym_destfinder_themes_relax theme_fam_friendly theme_food synonym_destfinder_themes_restaurants theme_seafood theme_sand_beaches theme_atmosphere theme_shopping theme_nightlife theme_sun_bathing theme_beaches_for_kids theme_scenery theme_people_watching theme_sunny theme_bar_hopping theme_friendly_people synonym_destfinder_themes_entertainment theme_water_sports theme_clean_streets theme_fishing theme_nature theme_gourmet theme_wild_swimming theme_warm_weather theme_walking theme_sunsets theme_swimming_pools theme_coastal_walks
eexpected output
myrtlebeach newyork
 */